name: Build and Publish NuGet Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore Dtwo.Plugins.MultiAccount.csproj
      
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

    - name: Build project
      run: dotnet build Dtwo.Plugins.MultiAccount.csproj --configuration Release /p:Version=${VERSION}

    - name: Pack NuGet package
      run: dotnet pack Dtwo.Plugins.MultiAccount.csproj --configuration Release /p:Version=${VERSION} --no-build --output .

    - name: Publish to GitHub Packages
      run: dotnet nuget push Dtwo.Plugins.MultiAccount.${VERSION}.nupkg --source "https://nuget.pkg.github.com/DtwoTool/index.json" --api-key ${{ secrets.GITHUB_TOKEN }}
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
